"""Create initial schema

Revision ID: 263179023266
Revises:
Create Date: 2026-08-02 15:46:19.772585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263179023266'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name='ck_teams_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_teams_name_ci', 'teams', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('SETUP', 'ACTIVE', 'COMPLETED', name='season_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_seasons_team_name')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('venue_type', sa.Enum('HOME', 'AWAY', 'NEUTRAL', name='venue_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPLETED', name='game_status'), nullable=False),
    sa.Column('opponent_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('grade_level', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LEFT_TEAM', name='roster_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'player_id', name='uq_season_rosters_season_player')
    )
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('season_roster_id', sa.Integer(), nullable=False),
    sa.Column('participation_status', sa.Enum('PLAYED', 'DID_NOT_PLAY', name='participation_status'), nullable=False),
    sa.Column('three_point_attempts', sa.Integer(), nullable=False),
    sa.Column('three_point_makes', sa.Integer(), nullable=False),
    sa.Column('two_point_attempts', sa.Integer(), nullable=False),
    sa.Column('two_point_makes', sa.Integer(), nullable=False),
    sa.Column('free_throw_attempts', sa.Integer(), nullable=False),
    sa.Column('free_throw_makes', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('deflections', sa.Integer(), nullable=False),
    sa.Column('personal_fouls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            participation_status <> 'DID_NOT_PLAY' OR (\n                three_point_attempts = 0 AND\n                three_point_makes = 0 AND\n                two_point_attempts = 0 AND\n                two_point_makes = 0 AND\n                free_throw_attempts = 0 AND\n                free_throw_makes = 0 AND\n                turnovers = 0 AND\n                assists = 0 AND\n                offensive_rebounds = 0 AND\n                defensive_rebounds = 0 AND\n                steals = 0 AND\n                deflections = 0 AND\n                personal_fouls = 0\n            )\n            ", name='ck_player_game_stats_dnp_zero_stats'),
    sa.CheckConstraint('\n            three_point_attempts >= 0 AND\n            three_point_makes >= 0 AND\n            two_point_attempts >= 0 AND\n            two_point_makes >= 0 AND\n            free_throw_attempts >= 0 AND\n            free_throw_makes >= 0 AND\n            turnovers >= 0 AND\n            assists >= 0 AND\n            offensive_rebounds >= 0 AND\n            defensive_rebounds >= 0 AND\n            steals >= 0 AND\n            deflections >= 0 AND\n            personal_fouls >= 0\n            ', name='ck_player_game_stats_nonnegative'),
    sa.CheckConstraint('free_throw_makes <= free_throw_attempts', name='ck_player_game_stats_ftm_lte_fta'),
    sa.CheckConstraint('three_point_makes <= three_point_attempts', name='ck_player_game_stats_3pm_lte_3pa'),
    sa.CheckConstraint('two_point_makes <= two_point_attempts', name='ck_player_game_stats_2pm_lte_2pa'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['season_roster_id'], ['season_rosters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'season_roster_id', name='uq_player_game_stats_game_roster')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game_stats')
    op.drop_table('season_rosters')
    op.drop_table('games')
    op.drop_table('seasons')
    op.drop_index('uq_teams_name_ci', table_name='teams')
    op.drop_table('teams')
    op.drop_table('players')
    op.execute("DROP TYPE IF EXISTS participation_status")
    op.execute("DROP TYPE IF EXISTS roster_status")
    op.execute("DROP TYPE IF EXISTS game_status")
    op.execute("DROP TYPE IF EXISTS venue_type")
    op.execute("DROP TYPE IF EXISTS season_status")
    # ### end Alembic commands ###
